version: "3.8"

services:
  notion-mcp-server:
    build:
      context: ..
      dockerfile: docker/Dockerfile.notion-mcp
    environment:
      - NOTION_TOKEN=${NOTION_TOKEN:-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}
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    restart: unless-stopped
    volumes:
      - ../src:/app/src
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import src.utils.notion_mcp_server; print('OK')",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
